export const styles = {
    page: { minHeight: "100vh", minHeight: "100dvh" },
    header: {
      position: "sticky",
      top: 0,
      zIndex: 5,
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "16px max(18px, env(safe-area-inset-right)) 16px max(18px, env(safe-area-inset-left))",
      paddingTop: "max(16px, env(safe-area-inset-top))",
      borderBottom: "1px solid",
    },
    brand: { display: "flex", alignItems: "center", gap: 12 },
    logo: {
      width: 44,
      height: 44,
      display: "grid",
      placeItems: "center",
      borderRadius: 14,
      border: "1px solid",
      fontSize: 22,
    },
    nav: { display: "flex", gap: 10, flexWrap: "wrap", justifyContent: "flex-end" },
    navBtn: {
      border: "1px solid",
      padding: "12px 16px",
      borderRadius: 14,
      cursor: "pointer",
      fontWeight: 700,
      minHeight: 44,
    },
    shell: {
      maxWidth: 980,
      margin: "0 auto",
      padding: "24px max(20px, env(safe-area-inset-left)) 48px max(20px, env(safe-area-inset-right))",
      paddingBottom: "max(48px, calc(env(safe-area-inset-bottom) + 32px))",
      transition: "padding 0.4s ease, max-width 0.4s ease",
    },
    shellFocus: {
      maxWidth: 520,
      padding: "16px max(20px, env(safe-area-inset-left)) 24px max(20px, env(safe-area-inset-right))",
      paddingBottom: "max(24px, calc(env(safe-area-inset-bottom) + 16px))",
    },
    card: {
      border: "1px solid",
      borderRadius: 24,
      padding: 20,
      boxShadow: "0 4px 32px rgba(0,0,0,0.25)",
      transition: "box-shadow 0.4s ease, padding 0.4s ease",
    },
    cardFocus: {
      boxShadow: "0 12px 48px rgba(0,0,0,0.4)",
    },
    h2: { margin: 0, fontSize: 22, letterSpacing: -0.02, lineHeight: 1.3 },
    p: { marginTop: 10, lineHeight: 1.6 },
    row: { display: "flex", gap: 12, marginTop: 14, flexWrap: "wrap" },
    primary: {
      border: "none",
      padding: "14px 20px",
      borderRadius: 16,
      cursor: "pointer",
      fontWeight: 700,
      minHeight: 48,
    },
    secondary: {
      background: "transparent",
      border: "1px solid",
      padding: "12px 18px",
      borderRadius: 14,
      cursor: "pointer",
      fontWeight: 700,
      minHeight: 44,
    },
    notice: { marginTop: 16, border: "1px solid", borderRadius: 18, padding: 14 },
    fakePanel: { marginTop: 12, border: "1px solid", borderRadius: 18, padding: 14 },
    choice: {
      background: "transparent",
      border: "1px solid",
      padding: "10px 12px",
      borderRadius: 14,
      cursor: "pointer",
      fontWeight: 800,
    },
    toggle: {
      width: "100%",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 16,
      borderRadius: 18,
      border: "1px solid",
      cursor: "pointer",
      textAlign: "left",
      gap: 12,
      minHeight: 56,
    },
    pill: {
      width: 46,
      height: 28,
      borderRadius: 999,
      border: "1px solid",
      padding: 4,
      display: "flex",
      alignItems: "center",
    },
    dot: {
      width: 20,
      height: 20,
      borderRadius: 999,
      background: "#fff",
      transition: "transform 180ms ease",
    },
    footer: {
      marginTop: 20,
      display: "flex",
      gap: 10,
      justifyContent: "center",
      flexWrap: "wrap",
      fontSize: 13,
      padding: "8px 0",
      transition: "opacity 0.4s ease",
    },
    footerFocus: {
      opacity: 0.25,
    },
  };
  